services:
  # Backend API Service
  - type: web
    name: skillswap-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: skillswap-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        fromService:
          type: web
          name: skillswap-frontend
          property: url
    healthCheckPath: /health

  # Frontend Web Service
  - type: web
    name: skillswap-frontend
    env: static
    plan: starter
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: skillswap-backend
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  # MongoDB Database
  - name: skillswap-mongodb
    plan: starter